import type { Company, Bill } from '@/types'

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'Sharma Groceries Pvt Ltd',
    gstin: '07AABCS1429B1Z1',
    email: 'groceries@sharma.com',
    port: 9000,
    totalBills: 28,
    syncedBills: 24,
    pendingBills: 3,
    errorBills: 1,
    mapping: {
      purchaseLedgers: ['Grocery Purchases'],
      cgstLedgers: ['Input CGST @2.5%'],
      sgstLedgers: ['Input SGST @2.5%'],
      igstLedgers: ['Input IGST'],
    },
    createdAt: '2025-01-10T00:00:00Z',
  },
  {
    id: 'c2',
    name: 'Electronics Hub',
    gstin: '27AAFCS5859R1Z4',
    email: 'accounts@ehub.in',
    port: 9000,
    totalBills: 15,
    syncedBills: 13,
    pendingBills: 0,
    errorBills: 2,
    mapping: {
      purchaseLedgers: ['Electronics Purchase'],
      cgstLedgers: ['Input CGST @9%'],
      sgstLedgers: ['Input SGST @9%'],
      igstLedgers: ['Input IGST'],
    },
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'c3',
    name: 'Raj Pharma Store',
    gstin: '09AAACR5055K1Z5',
    email: 'raj@pharmastore.com',
    port: 9000,
    totalBills: 9,
    syncedBills: 9,
    pendingBills: 0,
    errorBills: 0,
    mapping: null,
    createdAt: '2025-02-01T00:00:00Z',
  },
]

export const MOCK_BILLS: Record<string, Bill[]> = {
  c1: [
    {
      id: 'b1',
      companyId: 'c1',
      billNumber: 'INV-2024-001',
      vendorName: 'Fresh Farm Suppliers',
      vendorGstin: '07AABFS1234B1Z2',
      billDate: '2025-03-18',
      subtotal: 48810,
      cgstAmount: 1220,
      sgstAmount: 1220,
      igstAmount: 0,
      totalAmount: 52500,
      status: 'synced',
      syncedAt: '2025-03-18T14:30:00Z',
      lineItems: [
        { id: 'li1', description: 'Basmati Rice 25kg', hsnCode: '1006', quantity: 10, unit: 'BAG', unitPrice: 2800, gstRate: 5, amount: 29400 },
        { id: 'li2', description: 'Toor Dal 50kg',    hsnCode: '0713', quantity: 5,  unit: 'BAG', unitPrice: 4200, gstRate: 5, amount: 22050 },
      ],
      createdAt: '2025-03-18T10:00:00Z',
    },
    {
      id: 'b2',
      companyId: 'c1',
      billNumber: 'INV-2024-002',
      vendorName: 'National Traders',
      billDate: '2025-03-19',
      subtotal: 18000,
      cgstAmount: 450,
      sgstAmount: 450,
      igstAmount: 0,
      totalAmount: 18900,
      status: 'mapped',
      lineItems: [
        { id: 'li3', description: 'Cooking Oil 5L x12', hsnCode: '1512', quantity: 12, unit: 'PCS', unitPrice: 1400, gstRate: 5, amount: 17640 },
      ],
      createdAt: '2025-03-19T09:00:00Z',
    },
    {
      id: 'b3',
      companyId: 'c1',
      billNumber: 'APL/2025/0847',
      vendorName: 'Agro Products Ltd',
      billDate: '2025-03-21',
      subtotal: 30095,
      cgstAmount: 553,
      sgstAmount: 553,
      igstAmount: 0,
      totalAmount: 31200,
      status: 'parsed',
      lineItems: [
        { id: 'li4', description: 'Wheat Flour 50kg', hsnCode: '1101', quantity: 20, unit: 'BAG', unitPrice: 1400, gstRate: 0, amount: 28000 },
        { id: 'li5', description: 'Semolina 50kg',    hsnCode: '1103', quantity: 4,  unit: 'BAG', unitPrice: 800,  gstRate: 5, amount: 3360  },
      ],
      createdAt: '2025-03-21T08:00:00Z',
    },
  ],
  c2: [
    {
      id: 'b4',
      companyId: 'c2',
      billNumber: 'SI-4521',
      vendorName: 'Samsung Distributors',
      billDate: '2025-03-15',
      subtotal: 250000,
      cgstAmount: 22500,
      sgstAmount: 22500,
      igstAmount: 0,
      totalAmount: 295000,
      status: 'error',
      syncError: 'Ledger "Samsung Distributors" not found in Tally',
      lineItems: [
        { id: 'li6', description: 'Samsung 55" Smart TV', hsnCode: '8528', quantity: 5, unit: 'PCS', unitPrice: 50000, gstRate: 18, amount: 295000 },
      ],
      createdAt: '2025-03-15T11:00:00Z',
    },
    {
      id: 'b5',
      companyId: 'c2',
      billNumber: 'SI-4488',
      vendorName: 'LG Electronics Ltd',
      billDate: '2025-03-10',
      subtotal: 100000,
      cgstAmount: 9000,
      sgstAmount: 9000,
      igstAmount: 0,
      totalAmount: 118000,
      status: 'synced',
      syncedAt: '2025-03-11T10:00:00Z',
      lineItems: [
        { id: 'li7', description: 'LG Refrigerator 350L', hsnCode: '8418', quantity: 2, unit: 'PCS', unitPrice: 50000, gstRate: 18, amount: 118000 },
      ],
      createdAt: '2025-03-10T14:00:00Z',
    },
  ],
  c3: [
    {
      id: 'b6',
      companyId: 'c3',
      billNumber: 'MED-0091',
      vendorName: 'Cipla Distributors',
      billDate: '2025-03-08',
      subtotal: 38214,
      cgstAmount: 2293,
      sgstAmount: 2293,
      igstAmount: 0,
      totalAmount: 42800,
      status: 'synced',
      syncedAt: '2025-03-09T09:00:00Z',
      lineItems: [
        { id: 'li8', description: 'Paracetamol 500mg (strip)', hsnCode: '3004', quantity: 500, unit: 'STRIP', unitPrice: 8, gstRate: 12, amount: 4480 },
      ],
      createdAt: '2025-03-08T10:00:00Z',
    },
  ],
}

export const MOCK_TALLY_LEDGERS: { name: string; group: string }[] = [
  { name: 'Grocery Purchases',     group: 'Purchase Accounts' },
  { name: 'Electronics Purchase',  group: 'Purchase Accounts' },
  { name: 'Medicine Purchase',     group: 'Purchase Accounts' },
  { name: 'Raw Material Purchase', group: 'Purchase Accounts' },
  { name: 'Input CGST @2.5%',     group: 'Duties & Taxes' },
  { name: 'Input CGST @5%',       group: 'Duties & Taxes' },
  { name: 'Input CGST @9%',       group: 'Duties & Taxes' },
  { name: 'Input CGST @12%',      group: 'Duties & Taxes' },
  { name: 'Input CGST @18%',      group: 'Duties & Taxes' },
  { name: 'Input SGST @2.5%',     group: 'Duties & Taxes' },
  { name: 'Input SGST @5%',       group: 'Duties & Taxes' },
  { name: 'Input SGST @9%',       group: 'Duties & Taxes' },
  { name: 'Input SGST @12%',      group: 'Duties & Taxes' },
  { name: 'Input SGST @18%',      group: 'Duties & Taxes' },
  { name: 'Input IGST @5%',       group: 'Duties & Taxes' },
  { name: 'Input IGST @12%',      group: 'Duties & Taxes' },
  { name: 'Input IGST @18%',      group: 'Duties & Taxes' },
  { name: 'Fresh Farm Suppliers',  group: 'Sundry Creditors' },
  { name: 'National Traders',      group: 'Sundry Creditors' },
  { name: 'Samsung Distributors',  group: 'Sundry Creditors' },
  { name: 'LG Electronics Ltd',    group: 'Sundry Creditors' },
  { name: 'Cipla Distributors',    group: 'Sundry Creditors' },
  { name: 'Agro Products Ltd',     group: 'Sundry Creditors' },
  { name: 'Sundry Creditors',      group: 'Sundry Creditors' },
]
